### ISSUE TITLE
 隐藏文章的分类

### ISSUE THREAD

**Issue by larrylai19** [prinsss/hexo-hide-posts#16]
请问想弄一个隐藏文章的分类页面该如何实现？
就是像普通的分类那样但是里面都是隐藏的文章

**Comment by prinsss** [comment]
唔，目前对隐藏文章的分类实现好像有些问题，我尝试修复一下

**Comment by prinsss** [comment]
插件已更新至 0.1.1。在 `_config.yml` 中设置：

```yml
hide_posts:
  filter: hidden
  public_generators: [category]
```

然后给隐藏文章设置一个分类：

```yml
categories:
  - 机密
```

应该就可以在此分类中查看隐藏文章了。
