### ISSUE TITLE
public_generators: []不生效

### ISSUE THREAD

**Issue by forliuyifei** [prinsss/hexo-hide-posts#17]
我这样填的配置：
```
hide_posts:
  filter: hide
  # 常见的 generators 有：index, tag, category, archive, sitemap, feed, etc.
  public_generators: [category]
  noindex: true
```
但指定隐藏的文章并没有生成在categories目录下
