### ISSUE TITLE
[Bug] 使用该插件后生成时报错

### ISSUE THREAD

**Issue by zhang-stephen** [prinsss/hexo-hide-posts#27]
主题是hexo-theme-butterfly，报错如下，请问怎么解决？
<img width="1051" alt="截屏2022-12-17 12 23 19" src="https://user-images.githubusercontent.com/17326718/208224749-3d7dcd4b-2d13-4d31-bdef-5a1b02c8d01b.png">

配置：
```yaml
hide_posts:
  enable: true
  filter: secret
  public_generators:
    - tag
    - category
    - archive
  noindex: true
```
