### ISSUE TITLE
hexo-generator-feed 中没有隐藏文章

### ISSUE THREAD

**Issue by Pil0tXia** [prinsss/hexo-hide-posts#29]
我的配置：

```
# hexo-hide-posts
## https://github.com/prinsss/hexo-hide-posts
hide_posts:
  enable: true
  # 可以改成其他你喜欢的名字
  filter: hidden
  # 指定你想要传递隐藏文章的 generator，比如让所有隐藏文章在存档页面可见
  # 常见的 generators 有：index, tag, category, archive, sitemap, feed, etc.
  # 不常见的还有 xml (butterfly 主题的 hexo-generator-search 搜索，hexo-generator-searchdb 也是这个)
  public_generators: [archive,category,tag,sitemap,baidusitemap,xml,feed]
  # 为隐藏的文章添加 noindex meta 标签，阻止搜索引擎收录
  noindex: false
```

Hexo 插件：

```
$ hexo -v
INFO  Validating config
INFO
  ===================================================================
      #####  #    # ##### ##### ###### #####  ###### #      #   #
      #    # #    #   #     #   #      #    # #      #       # #
      #####  #    #   #     #   #####  #    # #####  #        #
      #    # #    #   #     #   #      #####  #      #        #
      #    # #    #   #     #   #      #   #  #      #        #
      #####   ####    #     #   ###### #    # #      ######   #
                            4.6.0
  ===================================================================
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.22621
node: 18.13.0
v8: 10.2.154.23-node.21
uv: 1.44.2
zlib: 1.2.13
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.51.0
napi: 8
llhttp: 6.0.10
uvwasi: 0.0.13
openssl: 3.0.7+quic
cldr: 42.0
icu: 72.1
tz: 2022f
unicode: 15.0
ngtcp2: 0.8.1
nghttp3: 0.7.0
```

隐藏文章（NSFW）：https://www.pil0txia.com/post/2022-12-09_chatgpt-teach-stable-diffusion-nsfw/

使用 hexo-generator-feed 生成的atom：https://www.pil0txia.com/atom.xml

期待您的回复，谢谢
