### ISSUE TITLE
能否仅对部分generator隐藏文章？

### ISSUE THREAD

**Issue by Hakuin123** [prinsss/hexo-hide-posts#32]
个人只想**在首页隐藏**一些杂乱的文章
但是按照目前插件的功能，只能手动把除了index以外的所有generator都添加到public_generators
包括但不限于：tag, category, archive, sitemap, feed, xml, json, wordcount………对于其他人来说可能会更多
能否添加一个反选功能？
还是挺需要这个的qwq

**Comment by Hakuin123** [comment]
翻了一下issues，发现 #26 也有这个需求，不过不知道 @xjunz 是怎么解决的

**Comment by prinsss** [comment]
Hi,

hexo-hide-posts 插件已经更新至 0.3.0，支持了更精细的 generator [黑白名单控制](https://github.com/prinsss/hexo-hide-posts/blob/master/README_ZH.md#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE)。反选功能可以这样实现：

```yaml
hide_posts:
  enable: true
  blocklist_generators: ['index']
  allowlist_generators: ['*']
```

如果新版本有任何问题，欢迎继续反馈。:)
