### ISSUE TITLE
期望能够有办法避免对site.posts.length的影响的方法

### ISSUE THREAD

**Issue by zhheo** [prinsss/hexo-hide-posts#37]
想要显示完整的文章总数，但是似乎隐藏的文章不计入总数。
请问有什么方式可以优化，感谢！

当前配置：
```yaml
# 隐藏文章
hide_posts:
  # 是否启用 hexo-hide-posts
  enable: true

  # 隐藏文章的 front-matter 标识，也可以改成其他你喜欢的名字
  filter: hidden

  # 为隐藏的文章添加 noindex meta 标签，阻止搜索引擎收录
  noindex: false

  # 设置白名单，白名单中的 generator 可以访问隐藏文章
  # 常见的 generators 有：index, tag, category, archive, sitemap, feed, etc.
  allowlist_generators: ['*']

  # 设置黑名单，黑名单中的 generator 不可以访问隐藏文章
  # 如果同时设置了黑名单和白名单，白名单的优先级更高
  blocklist_generators: ['index']
```
